### ISSUE TITLE
建议像Switchy一样能将代理协议分开

### ISSUE THREAD

**Issue by lsycxyj** [lovelywcm/autoproxy#4]
Switchy中能够针对不同的地址协议（如SSL、HTTP）来根据列表选择不同的代理，而Autoproxy是对任何协议只能用一个代理
某些代理软件需要根据不同协议将端口分开设置，autoproxy这时就得手动切换。这个是一个小功能，但可以帮到用户。希望能尽快增加，谢谢！

**Comment by lovelywcm** [comment]
请关注这一条： http://code.google.com/p/autoproxy/issues/detail?id=25

**Comment by lsycxyj** [comment]
我的意思不是将列表分开为各种的LIST来分别对应不同的协议，而是根据不同的协议请求（如地址栏是输入http、https等等）对应相同的list选择不同的代理（当然我不知道Autoproxy的具体实现是如何的），这样就可以不用分割list吧？（Switchy引用时也是可以直接引用GFW list，但同样实现了功能）。谢谢！
