### ISSUE TITLE
AutoProxy在Firefox 27上不显示代理规则

### ISSUE THREAD

**Issue by meteormatt** [lovelywcm/autoproxy#9]
AutoProxy在Firefox 27上不显示代理规则, 所以不能使用gfwList了.

![snap1](https://f.cloud.github.com/assets/424475/1622332/721863e2-56a3-11e3-8601-a0a1e684ef06.png)
可能我用的还是Aurora版本.
Firefox版本: 27
AutoProxy版本: 0.4b2.2013051811

![snap2](https://f.cloud.github.com/assets/424475/1622354/01a367d2-56a4-11e3-9a18-afd9e3b424ad.png)
![snap3](https://f.cloud.github.com/assets/424475/1622364/1d7650c8-56a4-11e3-96a0-e68802b9b5e5.png)

**Comment by johnmiroki** [comment]
确实又不好用了 （Firefox 27 Beta）

**Comment by xiuluo** [comment]
可以使用xthunder作者修复的版本，https://github.com/agunchan/autoproxy

**Comment by meteormatt** [comment]
@xiuluo 那个感觉还没合并进来.
AMO上面的也没更新.

**Comment by truebit** [comment]
Firefox 27 正式版也是这个问题

**Comment by yexingok** [comment]
请问作者有计划更新这个插件吗？

**Comment by truebit** [comment]
使用xthunder作者版本可行。已分享到百度盘：http://pan.baidu.com/s/1sjKxbwL

**Comment by meteormatt** [comment]
我是已经转用[FoxyProxy](http://getfoxyproxy.org/)了.
:broken_heart:
